default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: style_bootstrap_devtest
  username: rails_root
  password: Getpeace3689
  host: localhost

test:
  adapter: mysql2
  database: style_bootstrap_devtest
  username: rails_root
  password: Getpeace3689
  host: localhost

production:
  adapter: mysql
  database: style_bootstrap_prod
  username: rails_root
  password: Getpeace3689
  host: localhost
